### PR TITLE
Restore both parts of old history

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by jimregan** [comment]
@Juanpabl you might want to add the email address 'jpmart@unizar.es' so you'll show up as author

**Comment by Juanpabl** [comment]
@jimregan forgive my clumsiness... Where should I add my email address?

**Comment by sushain97** [comment]
@Juanpabl https://help.github.com/articles/adding-an-email-address-to-your-github-account/

**Comment by jimregan** [comment]
https://github.com/settings/emails
Nothing to forgive -- the incubator->trunk disconnect was me (though I'm pretty sure sourceforge "helped")

**Comment by Juanpabl** [comment]
Thanks, I have it already as my primary address!

**Pull request closed without merging**
